/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ulatina.interfaces;

import edu.ulatina.entidades.Producto;
import javax.swing.table.DefaultTableModel;
import edu.ulatina.entidades.Promocion;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author gavaf
 */
public class pnlAdminPromociones extends javax.swing.JPanel {

    DefaultTableModel model;
    //Limpia todos los text fields
    public void Clear(){
        txtNombre.setText(null);
        txtNombre.setText(null);
        txtCodigo.setText(null);
        txtPrecioPromo.setText(null);
        txtCantidad.setText(null);
        chbEstado.setSelected(false);
        dateFechaV.setCalendar(null);
        txtPrecio.setText(null);
        txtExistencias.setText(null);
        txtExistenciaMin.setText(null);
    }
    public pnlAdminPromociones() {
        initComponents();
        model = (DefaultTableModel) tableProductos.getModel();
        initInventario();
        initPromocion();
    }

    public void initInventario(){
        model  = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Precio");
        model.addColumn("Existencias");
        model.addColumn("Existencia Min");
        //Llena la tabla con constantes
        for(Producto prod: DiarioFacilTester.diarioFacil.getProductos()){
              model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProductos().indexOf(prod)), prod.getNombre(),Double.toString(prod.getPrecio()),Integer.toString(prod.getExistencias()), Integer.toString(prod.getExistenciaMin())});
          }
        tableProductos.setModel(model);
    }
    
    public void initPromocion(){
        model  = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Precio Promocional");
        model.addColumn("Estado");
        model.addColumn("Cantidad de Activación");
        model.addColumn("Fecha vencimiento");
        
        SimpleDateFormat formatter  = new SimpleDateFormat("yyyy-MM-dd hh:mm");
        //Llena la tabla con constantes
        for(Promocion prom: DiarioFacilTester.diarioFacil.getPromociones()){
          model.addRow(new Object[]{String.valueOf(DiarioFacilTester.diarioFacil.getPromociones().indexOf(prom)),  prom.getNombre(), Double.toString(prom.getPrecioPromocional()), Boolean.toString(prom.isEstado()), Integer.toString(prom.getCantidadActivacion()),formatter.format(prom.getFechaVencimiento())});
        }
        tablePromociones.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioPromo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        chbEstado = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtExistencias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtExistenciaMin = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePromociones = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        dateFechaV = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Promociones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Productos");

        jLabel3.setText("Precio Promocional:");

        jLabel4.setText("Estado:");

        jLabel5.setText("Fecha de Vencimiento:");

        jLabel7.setText("Cantidad de Activación:");

        chbEstado.setText("Activado");

        jLabel8.setText("Nombre:");

        jLabel9.setText("Código:");

        txtNombre.setEditable(false);

        txtCodigo.setEditable(false);

        btnDelete.setText("Eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setText("Precio:");

        txtPrecio.setEditable(false);

        jLabel10.setText("Existencias:");

        txtExistencias.setEditable(false);

        jLabel11.setText("Existencia Mínima:");

        txtExistenciaMin.setEditable(false);

        tablePromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablePromociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePromocionesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePromociones);

        jLabel12.setText("Promociones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(431, 431, 431)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtExistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 18, Short.MAX_VALUE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dateFechaV, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCodigo)
                                                .addComponent(txtPrecioPromo)
                                                .addComponent(chbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)))
                                        .addComponent(txtExistenciaMin, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtExistenciaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecioPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(chbEstado))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addComponent(dateFechaV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Agregar 
            /*if(DiarioFacilTester.diarioFacil.create(new Promocion(Double.parseDouble(txtPrecioPromo.getText()), Boolean.parseBoolean(chbEstado.getActionCommand()), Integer.parseInt(txtCantidad.getText()),txtNombre.getText(),tableProductos.getRowCount()+1,Double.parseDouble(txtPrecio.getText()),Integer.parseInt(txtExistencias.getText()),Integer.parseInt(txtExistenciaMin.getText())))){
                //Mensaje de agregado correctamente
                model.insertRow(model.getRowCount(), new Object[] {txtCodigo.getText(), txtNombre.getText(), txtPrecioPromo.getText(), chbEstado.getAction(), txtCantidad.getText()});
                initPromocion();       
            }  */
          if(txtPrecioPromo.getText().isEmpty() || txtCantidad.getText().isEmpty()){
            //Mensaje de error
             JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
          }else{
                boolean estado = false;
                if(chbEstado.isSelected())
                    estado = true;
                if(DiarioFacilTester.diarioFacil.create(new Promocion(Double.parseDouble(txtPrecioPromo.getText()),estado, Integer.parseInt(txtCantidad.getText()),txtNombre.getText(),tableProductos.getRowCount()+1,Double.parseDouble(txtPrecio.getText()),Integer.parseInt(txtExistencias.getText()),Integer.parseInt(txtExistenciaMin.getText()),dateFechaV.getDate()))){
                    initPromocion();
                    Clear();
                }else{
                    //Mensaje de errror den la creacion 
                    JOptionPane.showMessageDialog(null, "No se pudo crear la promocion", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                }
          }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        if(tablePromociones.getRowCount()>0){
            if(tablePromociones.getSelectedRow()>-1){
                if(txtPrecioPromo.getText().isEmpty() || txtCantidad.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                }else{
                    //Editar
                    boolean selected=false;
                    if(chbEstado.isSelected())
                        selected = true;
                    
                    if(DiarioFacilTester.diarioFacil.edit(Integer.parseInt(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 0).toString())  , new Promocion(Double.parseDouble(txtPrecioPromo.getText()), selected, Integer.parseInt(txtCantidad.getText()),txtNombre.getText(),Integer.parseInt(txtCodigo.getText()), Double.parseDouble(txtPrecio.getText()), Integer.parseInt(txtExistencias.getText()), Integer.parseInt(txtExistenciaMin.getText()),dateFechaV.getDate()))){
                        initPromocion();
                    }else{
                        JOptionPane.showMessageDialog(null, "Campos con informacion repetida", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                    }
                }
            }
        }
        Clear();
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(tablePromociones.getRowCount()>0){
            if(tablePromociones.getSelectedRow()>-1){
                int respuesta  = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar este producto?", "Sys", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                if(respuesta  == JOptionPane.YES_OPTION){
                    DiarioFacilTester.diarioFacil.delPromocion(Integer.parseInt(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 0).toString()));
                    initPromocion();
                }
            }
        }
        Clear();    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        //Muestra los datos de la fila seleccionada
        if(tableProductos.getRowCount()>0)
        if(tableProductos.getSelectedRow()>-1){
            txtCodigo.setText(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 0)));
            txtNombre.setText(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 1)));
            txtPrecio.setText(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 2)));
            txtExistencias.setText(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 3)));
            txtExistenciaMin.setText(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 4)));
        }
   
    }//GEN-LAST:event_tableProductosMouseClicked

    private void tablePromocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePromocionesMouseClicked
        //Muestra los datos de la fila seleccionada
        if(tablePromociones.getRowCount()>0)
        if(tablePromociones.getSelectedRow()>-1){
            txtCodigo.setText(String.valueOf(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 0)));
            txtNombre.setText(String.valueOf(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 1)));
            txtPrecioPromo.setText(String.valueOf(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 2)));
            txtCantidad.setText(String.valueOf(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 4)));
            txtExistencias.setText(String.valueOf(DiarioFacilTester.diarioFacil.getPromoExistencias(txtNombre.getText())));
            txtExistenciaMin.setText(String.valueOf(DiarioFacilTester.diarioFacil.getPromoExistenciaMinima(txtNombre.getText())));
            boolean estado = Boolean.parseBoolean(String.valueOf(tablePromociones.getValueAt(tablePromociones.getSelectedRow(), 3)));
            txtPrecio.setText(String.valueOf(DiarioFacilTester.diarioFacil.getPromoPrecio(txtNombre.getText())));
            dateFechaV.setDate(DiarioFacilTester.diarioFacil.getPromoDate(txtNombre.getText()));
            chbEstado.setSelected(estado);
        }
    }//GEN-LAST:event_tablePromocionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JCheckBox chbEstado;
    private com.toedter.calendar.JDateChooser dateFechaV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTable tablePromociones;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExistenciaMin;
    private javax.swing.JTextField txtExistencias;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioPromo;
    // End of variables declaration//GEN-END:variables
}
