/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ulatina.interfaces;


import edu.ulatina.entidades.Proveedor;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nvidi
 */
public class pnlAdminProveedorHome extends javax.swing.JPanel {
    DefaultTableModel model  = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
    }
    };
    /**
     * Creates new form pnlAdminProveedorHome
     */
    public pnlAdminProveedorHome() {
        initComponents();
        initProveedores();
        initFiltros();
    }
    
    private void initFiltros(){
        cbFiltros.removeAllItems();
        cbFiltros.addItem("Empresa");
        cbFiltros.addItem("Numero de contacto");
        cbFiltros.addItem("Producto");
        cbFiltros.addItem("Nombre");
    }
    
    public void initProveedores(){
        model  = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Cedula");
        model.addColumn("Empresa");
        model.addColumn("Email");
        model.addColumn("Numero contacto");
        for(Proveedor prov : DiarioFacilTester.diarioFacil.getProveedores()){
          model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProveedores().indexOf(prov)), prov.getNombre(),prov.getApellido(),prov.getCedula(),prov.getEmpresa(),prov.getEmail(),prov.getNumeroContacto()});
        }
        jtbProveedores.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbProveedores = new rojerusan.RSTableMetro();
        jPanel3 = new javax.swing.JPanel();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new rojeru_san.RSMTextFull();
        txtNumeroContacto = new rojeru_san.RSMTextFull();
        txtApellido = new rojeru_san.RSMTextFull();
        txtCedula = new rojeru_san.RSMTextFull();
        txtEmpresa = new rojeru_san.RSMTextFull();
        btnEdit = new rojerusan.RSButtonIconI();
        btnClean = new rojerusan.RSButtonIconI();
        btnAdd = new rojerusan.RSButtonIconI();
        btnDelete = new rojerusan.RSButtonIconI();
        jLabel7 = new javax.swing.JLabel();
        tXtCorreo = new rojeru_san.RSMTextFull();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        cbFiltros = new rojerusan.RSComboMetro();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(957, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 112, 192));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(766, 90));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar proveedores");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        rSPanelShadow1.setName("rSPanelShadow1"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jtbProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbProveedores.setName("jtbProveedores"); // NOI18N
        jtbProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbProveedores);

        rSPanelShadow1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(204, 204, 204));
        rSPanelGradiente1.setName("rSPanelGradiente1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre de Empresa:");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Apellidos:");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cédula:");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Correo:");
        jLabel5.setName("jLabel5"); // NOI18N

        txtNombre.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.setPlaceholder("Pablo...");

        txtNumeroContacto.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtNumeroContacto.setName("txtNumeroContacto"); // NOI18N
        txtNumeroContacto.setPlaceholder("900239...");

        txtApellido.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtApellido.setName("txtApellido"); // NOI18N
        txtApellido.setPlaceholder("Gutierrez...");

        txtCedula.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtCedula.setName("txtCedula"); // NOI18N
        txtCedula.setPlaceholder("14435CX...");

        txtEmpresa.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        txtEmpresa.setName("txtEmpresa"); // NOI18N
        txtEmpresa.setPlaceholder("Coca cola...");

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ulatina/ejemplos/img/icons8-edit-24.png"))); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ulatina/ejemplos/img/icons8-clear-formatting-24.png"))); // NOI18N
        btnClean.setText("Limpiar campos");
        btnClean.setName("btnClean"); // NOI18N
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ulatina/ejemplos/img/icons8-add-24.png"))); // NOI18N
        btnAdd.setText("Agregar");
        btnAdd.setName("btnAdd"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ulatina/ejemplos/img/icons8-delete-24.png"))); // NOI18N
        btnDelete.setText("Eliminar");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Numero contacto:");
        jLabel7.setName("jLabel7"); // NOI18N

        tXtCorreo.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        tXtCorreo.setName("tXtCorreo"); // NOI18N
        tXtCorreo.setPlaceholder("ejemplo@gmail.com...");

        javax.swing.GroupLayout rSPanelGradiente1Layout = new javax.swing.GroupLayout(rSPanelGradiente1);
        rSPanelGradiente1.setLayout(rSPanelGradiente1Layout);
        rSPanelGradiente1Layout.setHorizontalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumeroContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tXtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        rSPanelGradiente1Layout.setVerticalGroup(
            rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(tXtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtNumeroContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(rSPanelGradiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rSPanelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSMTextFull1.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        rSMTextFull1.setName("rSMTextFull1"); // NOI18N
        rSMTextFull1.setPlaceholder("Buscar...");
        rSMTextFull1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rSMTextFull1KeyTyped(evt);
            }
        });

        cbFiltros.setName("cbFiltros"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(jtbProveedores.getRowCount()>0){
            if(jtbProveedores.getSelectedRow()>-1){
                if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtCedula.getText().isEmpty()|| txtEmpresa.getText().isEmpty() || tXtCorreo.getText().isEmpty() || txtNumeroContacto.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                }else{
                    //Editar
                    if(DiarioFacilTester.diarioFacil.edit(jtbProveedores.getSelectedRow(), new Proveedor(txtEmpresa.getText(),txtNumeroContacto.getText(),txtCedula.getText(),txtNombre.getText(),txtApellido.getText(),tXtCorreo.getText()))){
                        initProveedores();
                    }else{
                         JOptionPane.showMessageDialog(null, "Campos con informacion repetida", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                    }
                }
            }
        }
        
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      //<editor-fold defaultstate="collapsed" desc="Credenciales_de_super_usuario" >
          if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtCedula.getText().isEmpty()|| txtEmpresa.getText().isEmpty() || tXtCorreo.getText().isEmpty() || txtNumeroContacto.getText().isEmpty()){
            //Mensaje de error
             JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
          }
          else{
            //Agregar 
            if(DiarioFacilTester.diarioFacil.create(new Proveedor(txtEmpresa.getText(),txtNumeroContacto.getText(),txtCedula.getText(),txtNombre.getText(),txtApellido.getText(),tXtCorreo.getText()))){
                //Mensaje de agregado correctamente
                initProveedores();
            }else{
                //Mensaje de error
                 JOptionPane.showMessageDialog(null, "Campos con informacion repetida", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
            }
          }
      //</editor-fold>
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        tXtCorreo.setText("");
        txtEmpresa.setText("");
        txtNumeroContacto.setText("");
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jtbProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbProveedoresMouseClicked
        if(jtbProveedores.getRowCount()>0)
            if(jtbProveedores.getSelectedRow()>-1){
                    txtNombre.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 1)));
                    txtApellido.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 2)));
                    txtCedula.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 3)));
                    txtEmpresa.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 4)));
                    tXtCorreo.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 5)));
                    txtNumeroContacto.setText(String.valueOf(jtbProveedores.getValueAt(jtbProveedores.getSelectedRow(), 6)));
                    
            }
            
    }//GEN-LAST:event_jtbProveedoresMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(jtbProveedores.getRowCount()>0){
            if(jtbProveedores.getSelectedRow()>-1){
                int respuesta  = JOptionPane.showConfirmDialog(null, "Seguro desea eliminar este proveedor?", "Sys", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                if(respuesta  == JOptionPane.YES_OPTION){
                    //Consultar si el proveedor tiene productos registrados en el futuro jaja
                    DiarioFacilTester.diarioFacil.deleteProveedor(jtbProveedores.getSelectedRow());
                    initProveedores();
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rSMTextFull1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rSMTextFull1KeyTyped
        // TODO add your handling code here:
        model  = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Cedula");
        model.addColumn("Empresa");
        model.addColumn("Email");
        model.addColumn("Numero contacto");
        if(cbFiltros.getSelectedItem().toString().equals("Empresa")){      
            for(Object prov : DiarioFacilTester.diarioFacil.read("empresa", rSMTextFull1.getText(), DiarioFacilTester.diarioFacil.getProveedores())){
              model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProveedores().indexOf((Proveedor)prov)), ((Proveedor)prov).getNombre(),((Proveedor)prov).getApellido(),((Proveedor)prov).getCedula(),((Proveedor)prov).getEmpresa(),((Proveedor)prov).getEmail(),((Proveedor)prov).getNumeroContacto()});
            }
            jtbProveedores.setModel(model);
        }else if (cbFiltros.getSelectedItem().toString().equals("Numero de contacto")){
            for(Object prov : DiarioFacilTester.diarioFacil.read("numeroContacto", rSMTextFull1.getText(), DiarioFacilTester.diarioFacil.getProveedores())){
              model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProveedores().indexOf((Proveedor)prov)), ((Proveedor)prov).getNombre(),((Proveedor)prov).getApellido(),((Proveedor)prov).getCedula(),((Proveedor)prov).getEmpresa(),((Proveedor)prov).getEmail(),((Proveedor)prov).getNumeroContacto()});
            }
            jtbProveedores.setModel(model);
        }else if(cbFiltros.getSelectedItem().toString().equals("Producto")){
            for(Object prov : DiarioFacilTester.diarioFacil.read("productos", rSMTextFull1.getText(), DiarioFacilTester.diarioFacil.getProveedores())){
              model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProveedores().indexOf((Proveedor)prov)), ((Proveedor)prov).getNombre(),((Proveedor)prov).getApellido(),((Proveedor)prov).getCedula(),((Proveedor)prov).getEmpresa(),((Proveedor)prov).getEmail(),((Proveedor)prov).getNumeroContacto()});
            }
            jtbProveedores.setModel(model); 
        }else{
            for(Object prov : DiarioFacilTester.diarioFacil.read("nombre", rSMTextFull1.getText(), DiarioFacilTester.diarioFacil.getProveedores())){
              model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProveedores().indexOf((Proveedor)prov)), ((Proveedor)prov).getNombre(),((Proveedor)prov).getApellido(),((Proveedor)prov).getCedula(),((Proveedor)prov).getEmpresa(),((Proveedor)prov).getEmail(),((Proveedor)prov).getNumeroContacto()});
            }
            jtbProveedores.setModel(model); 
        }

    }//GEN-LAST:event_rSMTextFull1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btnAdd;
    private rojerusan.RSButtonIconI btnClean;
    private rojerusan.RSButtonIconI btnDelete;
    private rojerusan.RSButtonIconI btnEdit;
    private rojerusan.RSComboMetro cbFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSTableMetro jtbProveedores;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSMTextFull tXtCorreo;
    private rojeru_san.RSMTextFull txtApellido;
    private rojeru_san.RSMTextFull txtCedula;
    private rojeru_san.RSMTextFull txtEmpresa;
    private rojeru_san.RSMTextFull txtNombre;
    private rojeru_san.RSMTextFull txtNumeroContacto;
    // End of variables declaration//GEN-END:variables
}
