/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ulatina.interfaces;

import edu.ulatina.entidades.Producto;
import javax.swing.table.DefaultTableModel;
import edu.ulatina.entidades.Paquete;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gavaf
 */
public class pnlAdminPaquetes extends javax.swing.JPanel {

    /**
     * Creates new form pnlAdminPaquetes
     */
    DefaultTableModel model;
    DefaultComboBoxModel cbModel;
    //Limpia todos los campos
    public void Clear(){
        txtCodigo.setText(null);
        txtPrecioPaquete.setText(null);
        cbProductos.removeAllItems();
        txtPrecioPaq.setText(null);
        this.txtNombrePaquete.setText("");
        cbProductosAg.removeAllItems();
    }
    
    public pnlAdminPaquetes() {
        initComponents();
        model = (DefaultTableModel) tableProductos.getModel();
        initInventario();
        initPaquete();
    }

    public void initInventario(){
        model  = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        
        model.addColumn("Codigo");
        model.addColumn("Nombre");
        model.addColumn("Precio");
        model.addColumn("Existencias");
        model.addColumn("Existencia Mínima");
        //Llena la tabla con constantes
        for(Producto prod: DiarioFacilTester.diarioFacil.getProductos()){
          model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getProductos().indexOf(prod)), prod.getNombre(), Double.toString(prod.getPrecio()), Integer.toString(prod.getExistencias()), Integer.toString(prod.getExistenciaMin())});
        }
        tableProductos.setModel(model);
    }
    
    public void initPaquete(){
        model = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        model.addColumn("Código Paquete");
        model.addColumn("Nombre Paquete:");
        model.addColumn("Precio Paquete");
        //Llena la tabla con constantes
        for(Paquete paq: DiarioFacilTester.diarioFacil.getPaquetes()){
            model.addRow(new String[]{String.valueOf(DiarioFacilTester.diarioFacil.getPaquetes().indexOf(paq)),paq.getNombre(), String.valueOf(paq.getPrecioPromocional())});
        }
        tablePaquetes.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePaquetes = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDelPaquete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtPrecioPaquete = new javax.swing.JTextField();
        cbProductosAg = new javax.swing.JComboBox<String>();
        jLabel7 = new javax.swing.JLabel();
        cbProductos = new javax.swing.JComboBox<String>();
        btnAddDefo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioPaq = new javax.swing.JTextField();
        btnDelProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNombrePaquete = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Paquetes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        jLabel2.setText("Productos");

        tableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProductos);

        tablePaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablePaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePaquetesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePaquetes);

        jLabel3.setText("Paquetes");

        jLabel4.setText("Productos del Paquete:");

        jLabel5.setText("Precio del Paquete:");

        btnDelPaquete.setText("Eliminar Paquete");
        btnDelPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelPaqueteActionPerformed(evt);
            }
        });

        btnEdit.setText("Editar Paquete");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel6.setText("Código del Paquete:");

        txtCodigo.setEditable(false);

        jLabel7.setText("Productos a Agregar:");

        btnAddDefo.setText("Generar paquete");
        btnAddDefo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDefoActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio del Paquete:");

        btnDelProducto.setText("Eliminar Producto del Paquete");
        btnDelProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelProductoActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre de Paquete: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombrePaquete))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cbProductosAg, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecioPaq, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddDefo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrecioPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbProductosAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelProducto)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecioPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDefo))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombrePaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecioPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelPaquete)
                    .addComponent(btnEdit)
                    .addComponent(btnClear))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductosMouseClicked
        String producto =String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 1));
        boolean check=false;
        for (int i = 0; i <cbProductosAg.getItemCount() ; i++) {
            if(cbProductosAg.getItemAt(i).equals(producto)){
                
                check = true;
            }else{
                check=false;
            }
        }
        
        if(check == false){
            cbProductosAg.addItem(String.valueOf(tableProductos.getValueAt(tableProductos.getSelectedRow(), 1)));
        }else{
            JOptionPane.showMessageDialog(null, "Producto ya está en lista!");
        }
        
    }//GEN-LAST:event_tableProductosMouseClicked

    private void tablePaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePaquetesMouseClicked
        //Muestra los datos de la fila seleccionada
        if(tablePaquetes.getRowCount()>0)
        if(tablePaquetes.getSelectedRow()>-1){
            txtCodigo.setText(String.valueOf(tablePaquetes.getValueAt(tablePaquetes.getSelectedRow(), 0)));
            txtPrecioPaquete.setText(String.valueOf(tablePaquetes.getValueAt(tablePaquetes.getSelectedRow(), 2)));
           
        }
        
        List<Paquete> paquetes = DiarioFacilTester.diarioFacil.getPaquetes();
            Paquete paquete  = paquetes.get(Integer.parseInt(txtCodigo.getText()));
            List<Producto> productos = paquete.getProductos();
            for (int i = 0; i < productos.size(); i++) {
               String nombre = productos.get(i).getNombre();
               cbProductos.addItem(nombre);
            }
            
            
 
            for (int i = 0; i < productos.size(); i++) {
               String nombre = productos.get(i).getNombre();
               this.cbProductosAg.addItem(nombre);
            }
    }//GEN-LAST:event_tablePaquetesMouseClicked

    private void btnAddDefoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDefoActionPerformed
                //Confirmar al usuario si esos son los productos que quiere agregar al paquete
           List<Producto> productos= DiarioFacilTester.diarioFacil.getProductos();
           List<Producto> inproductos = new ArrayList<>();
              List<Paquete> dummyPrueba = DiarioFacilTester.diarioFacil.getPaquetes();
            if(txtPrecioPaq.getText().equals("") || this.txtNombrePaquete.getText().equals("")){
            //Mensaje de error
             JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Sys", JOptionPane.ERROR_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
          }
                else{
                int respuesta  = JOptionPane.showConfirmDialog(null, "¿Seguro que desea agregar estos productos?", "Sys", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, new ImageIcon("src/edu/ulatina/ejemplos/img/icons8-error-32.png"));
                if(respuesta  == JOptionPane.YES_OPTION){
                    //Si la respuesta es si, entonces agrega el paquete                            //No se si esto del Combo funciona bien
                
                    for (int i = 0; i < this.cbProductosAg.getModel().getSize(); i++) {
                        for(Producto pro : DiarioFacilTester.diarioFacil.getProductos()){
                            if(pro.getNombre().equals(cbProductosAg.getModel().getElementAt(i).toString())){
                                inproductos.add(pro);
                            }
                        }
                    }
                  
                  boolean check = false;  
               
                    for (int i = 0; i < dummyPrueba.size(); i++) {
                        String nombre = dummyPrueba.get(i).getNombre();
                        if(this.txtNombrePaquete.getText().equals(nombre)){
                            /* JOptionPane.showMessageDialog(null, "El paquete ya se encuentra registrado! cambie el nombre");*/
                             check = true;
                             i =  dummyPrueba.size()+1;
                        }else{
                            check = false;
                        }
                    }
                    if(check == false){
                        Paquete paquete = new Paquete(inproductos,Double.parseDouble(this.txtPrecioPaq.getText()), this.txtNombrePaquete.getText());
                          DiarioFacilTester.diarioFacil.addPaquete(paquete);
                          initPaquete();
                         JOptionPane.showMessageDialog(null, "Paquete Generado!");
                    }else{
                        JOptionPane.showMessageDialog(null, "El paquete ya se encuentra registrado! cambie el nombre");
                    }
                  Clear();
                }
                }
            
    }//GEN-LAST:event_btnAddDefoActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDelPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelPaqueteActionPerformed
       int index = Integer.valueOf(this.txtCodigo.getText());
       DiarioFacilTester.diarioFacil.eliminarPaquete(index);
       initPaquete();
        Clear();
    }//GEN-LAST:event_btnDelPaqueteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     /*Editar Paquete*/
     List<Producto> productos= DiarioFacilTester.diarioFacil.getProductos();     
     List<Producto> inproductos = new ArrayList<>();
     List<Paquete> dummyPrueba = DiarioFacilTester.diarioFacil.getPaquetes(); 
     
       for (int i = 0; i < this.cbProductosAg.getModel().getSize(); i++) {
                        for(Producto pro : DiarioFacilTester.diarioFacil.getProductos()){
                            if(pro.getNombre().equals(cbProductosAg.getModel().getElementAt(i).toString())){
                                inproductos.add(pro);
                            }
                        }
                    }
                      
                    try{
                        String nombre = dummyPrueba.get(Integer.parseInt(this.txtCodigo.getText())).getNombre();
                        Paquete paquete = new Paquete(inproductos,Double.parseDouble(this.txtPrecioPaquete.getText()),nombre);
                        DiarioFacilTester.diarioFacil.editarPaquete(Integer.parseInt(this.txtCodigo.getText()), paquete);
                                              
                         JOptionPane.showMessageDialog(null, "Paquete Editado!");
                    }catch(Exception e){
                        
                         JOptionPane.showMessageDialog(null, "Error al editar");
                    }
                    initPaquete();
                         
                    Clear(); 
                  
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDelProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelProductoActionPerformed
        cbProductosAg.removeItem(cbProductosAg.getSelectedItem());
    }//GEN-LAST:event_btnDelProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDefo;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelPaquete;
    private javax.swing.JButton btnDelProducto;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JComboBox<String> cbProductosAg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePaquetes;
    private javax.swing.JTable tableProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombrePaquete;
    private javax.swing.JTextField txtPrecioPaq;
    private javax.swing.JTextField txtPrecioPaquete;
    // End of variables declaration//GEN-END:variables
}
